version: '3.1'
services:
  mysql:
    image: mysql:8.0.30
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=test
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
